/**
 * CLI definition.
 *
 * Generated by ph-clint. Regions bracketed by @clint:begin/@clint:end
 * markers are rewritten by ph-clint when the project spec changes.
 * Everything outside the markers is user-editable and preserved.
 */
// @clint:begin imports
import { defineCli } from '@powerhousedao/ph-clint';
import path from 'node:path';
import { CLI_NAME, CLI_VERSION, CLI_ROOT } from './config.js';
import { configSchema, secretsSchema } from './framework.js';
import { createAgent } from './agents/agent.js';
import { migrateCommand } from './commands/migrate.js';
import { validateCommand } from './commands/validate.js';
import { selfUpdateCommand } from './commands/self-update.js';
// @clint:end imports

export const cli = defineCli({
  name: CLI_NAME,
  version: CLI_VERSION,
  description: `${CLI_NAME} v${CLI_VERSION}`,
  configSchema,
  secretsSchema,

  // @clint:begin commands
  commands: [migrateCommand, validateCommand, selfUpdateCommand],
  // @clint:end commands

  // @clint:begin services
  services: [],
  // @clint:end services

  // @clint:begin triggers
  triggers: [],
  // @clint:end triggers

  // @clint:begin prompts
  prompts: {
    artifacts: [path.join(CLI_ROOT, 'gen', 'skills'), path.join(CLI_ROOT, 'dist', 'gen', 'skills')],
    agents: {
      'ph-porter-agent': {
        name: 'role',
        sections: [
          'role.md',
          'modes.md',
          'workflow.md',
          'guardrails.md',
        ],
        skills: [],
      },
    },
    skills: {},
  },
  // @clint:end prompts

  // @clint:begin events
  events: {},
  // @clint:end events

  // @clint:begin interactive
  interactive: {
    welcome: ({ workdir }) =>
      [
        `${CLI_NAME} v${CLI_VERSION}`,
        `Workdir: ${workdir}`,
        '',
        'Type a message to talk to the agent, or /help for commands.',
      ].join('\n'),
  },
  // @clint:end interactive
});

// @clint:begin reactor
// @clint:end reactor

// @clint:begin mastra
cli.configureAgent(createAgent);
// @clint:end mastra
